config/routes.rb
Yona::Application.routes.draw do

  resources :feeds, shallow: true do
    resources :articles
    collection do
      match :upload, via: [:get, :post]
      post :fetch
    end
  end

  root to: 'top#index'

  get "/auth/:provider/callback" => "sessions#callback"
  get "/auth/failure" => "sessions#failure"
  get "/logout" => "sessions#destroy", :as => :logout
end

app/models/feed.rb
# == Schema Information
#
# Table name: feeds
#
#  id               :integer          not null, primary key
#  url              :string(255)      not null
#  title            :string(255)      not null
#  html_url         :string(255)      not null
#  kind             :string(255)      not null
#  creator          :string(255)
#  etag             :string(255)
#  last_modified_at :datetime
#  articles_count   :integer          default(0), not null
#  created_at       :datetime
#  updated_at       :datetime
#

class Feed < ActiveRecord::Base
  belongs_to :user
  has_many :feed_tags
  has_many :articles

  def tags(user)
    tag_ids = feed_tags.pluck(:tag_id)
    Tag.where("id in (?)", tag_ids)
  end

  def self.import(user, xml_string)
    data = Hashie::Mash.new Hash.from_xml(xml_string)

    transaction do
      self.import_outline(user, data.opml.body.outline, nil)
    end
  end

  def self.import_outline(user, node, parent)
    if node.is_a? Array
      node.map{|r| import_outline(user, r, parent)}
    elsif node.outline
      import_outline(user, node.outline, node)
    else
      feed = Feed.where(url: node.xmlUrl).first_or_create({
        title: node.title,
        html_url: node.htmlUrl,
        # opml importでは固定
        kind: :rss,
      })
      UserFeed.where(
        user_id: user.id,
        feed_id: feed.id,
      ).first_or_create

      if parent
        tag = Tag.where(
          user_id: user.id,
          label: parent.title,
        ).first_or_create

        FeedTag.where(
          feed_id: feed.id,
          tag_id: tag.id,
        ).first_or_create

      end
    end
  end

  def self.fetch_all
    transaction do
      Feed.all.map(&:fetch)
    end
  end

  MIN_FETCH_TERM_MINUTES = 5
  def fetch
    return if last_fetched_at && last_fetched_at > MIN_FETCH_TERM_MINUTES.minutes.ago
    fetch_now
  end

  def fetch_now(reload: false)
    data = nil
    begin
      options = {}
      unless reload
        options[:if_modified_since] = last_modified_at if last_modified_at
        options[:if_none_match] = etag if etag
      end

      raw = Feedzirra::Feed.fetch_raw(url, options)
      data = Feedzirra::Feed.parse(raw.strip) if raw

      self.last_fetched_at = DateTime.now
      if !data || (!reload && last_modified_at && last_modified_at >= data.last_modified)
        logger.debug "no updated data: " + url
        self.save1
        return
      end
      # loafah.scrub :pruneで有害タグを削除
      data.sanitize_entries!
    rescue => error
      logger.warn "fetch error:" + url + " " + error.to_s
      return
    end

    # vim-users.jpのデータが取得できないがnilにはならない
    return unless data.title

    self.title = data.title
    self.etag  = data.etag
    self.last_modified_at = data.last_modified
    self.save!

    data.entries.map do |e|
      begin
        article = Article.where(url: e.url).first

        if article
          next if article.published_at >= e.published && !reload
          # TODO 既読削除
          article.update_attributes!(
            title: e.title,
            content: e.content || e.summary,
            author: e.author,
            url: e.url,
            published_at: e.published,
          )
        else
          Article.create(
            feed: self,
            title: e.title,
            content: e.content || e.summary,
            author: e.author,
            url: e.url,
            published_at: e.published,
          )
        end

      rescue => error
        logger.warn "save error:" + data.url + " " + error.to_s
        return
      end
    end
  end

  def self.load_test
    raise unless Rails.env.development?
    user = User.where(id: 1).first_or_create
    Feed.import(user, File.open(Rails.root.to_s + "/doc/sample.xml").read)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  def default_serializer_options
    {root: false}
  end

  def index
    @unreads = []

    # TODO モデルへ
    @unread_user_feeds = UserFeed.unreads(current_user)
    current_user.tags.each do |tag|
      user_feeds = UserFeed.select_by_tag(@unread_user_feeds, tag)
      next if user_feeds.empty?
      uc = UnreadsContainer.new
      uc.tag = tag
      uc.user_feeds = user_feeds
      @unreads << uc
    end

    respond_to do |format|
      format.html { render partial: 'feeds'}
      format.json { render json: @unreads, each_serializer: UnreadsContainerSerializer }
    end
  end

  def show
  end

  def new
    @feed = Feed.new
  end

  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render action: 'show', status: :created, location: @feed }
      else
        format.html { render action: 'new' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end

  def upload
    if request.method == "POST"
      Feed.import current_user, request.params[:opml_file].read
      Feed.fetch_all
      redirect_to :root
    end
  end

  def fetch
    current_user.feeds.each{|f| f.fetch}
    render json: 'success'
  end

  private
    def set_feed
      @feed = Feed.find(params[:id])
    end

    def feed_params
      params.require(:feed).permit(:title, :url, :html_url, :kind)
    end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_feeds.html.haml
- @unreads.each do |u|
  %li.nav-header
    = u.tag.label
    - u.user_feeds.each do |uf|
    - feed = uf.feed
      %li
        = link_to(url_for(controller: :articles, action: :index, feed_id: feed.id), remote: true, 'data-type' => :html, class: "feed_link") do
          .feed_title
            = image_tag "#{feed.html_url}favicon.ico", alt: feed.title, class: 'favicon'
            = uf.feed.title
          %span.badge.unread_articles_count= uf.unread_articles_count

app/views/feeds/_form.html.haml
= form_for @feed do |f|
  - if @feed.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feed.errors.count, "error")} prohibited this feed from being saved:"
      %ul
        - @feed.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :html_url
    = f.text_field :html_url
  .field
    = f.label :kind
    = f.text_field :kind
  .actions
    = f.submit 'Save'

app/views/feeds/edit.html.haml
%h1 Editing feed

= render 'form'

= link_to 'Show', @feed
\|
= link_to 'Back', feeds_path

app/views/feeds/index.html.haml
- @unreads.each do |u|
  %li.nav-header
    = u.tag.label
    - u.user_feeds.each do |uf|
    - feed = uf.feed
      %li
        = link_to(url_for(controller: :articles, action: :index, feed_id: feed.id), remote: true, 'data-type' => :html, class: "feed_link") do
          .feed_title
            = image_tag "#{feed.html_url}favicon.ico", alt: feed.title, class: 'favicon'
            = uf.feed.title
          %span.badge.unread_articles_count= uf.unread_articles_count

app/views/feeds/new.html.haml
%h1 New feed

= render 'form'

= link_to 'Back', feeds_path

app/views/feeds/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @feed.title
%p
  %b Feed url:
  = @feed.url
%p
  %b Html url:
  = @feed.html_url
%p
  %b Kind:
  = @feed.kind

= link_to 'Edit', edit_feed_path(@feed)
\|
= link_to 'Back', feeds_path

app/views/feeds/upload.html.haml
%h1 upload opml

=form_tag 'upload', multipart: true do
  =file_field_tag "opml_file"
  =submit_tag 'Import'

= link_to 'Feeds', feeds_path